BasicMultiFilter.PhotoAlertQuery: add missing ClassVar type
This caused pytest to fail with:
TypeError: 1 validation error for BasicMultiFilter
filters -> 0
  'member_descriptor' object is not subscriptable (type=type_error)